name: My Workflow
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello my love!"
      - name: Print Goodnight
        run: echo "Goodnight my love!"
